### ISSUE TITLE
Cursor comparison error when comparing date values

### ISSUE THREAD

**Issue by SDepn** [utPLSQL/utPLSQL#1020]
# Description
We are having issues with comparing date values in cursors. Right now we are running on v3.1.3.2402 where everything works fine. However after updating to v3.1.7.3096, date comparisons are not working anymore. We always run into the following error:
```
p_test
  p_test
    test123 [,025 sec] (FAILED - 1)
 
Failures:
 
  1) test_proc
      ORA-01861: literal does not match format string
      ORA-06512: at "UT3.UT_DATA_VALUE_REFCURSOR", line 338
      ORA-06512: at "UT3.UT_DATA_VALUE_REFCURSOR", line 333
      ORA-06512: at "UT3.UT_DATA_VALUE_REFCURSOR", line 386
      ORA-06512: at "UT3.UT_EQUAL", line 231
      ORA-06512: at "UT3.UT_EXPECTATION", line 26
      ORA-06512: at "UT3.UT_EXPECTATION", line 138
      ORA-06512: at "LOGICPRD.P_TEST_UT", line 41
      ORA-06512: at "UT3.UT_DATA_VALUE_REFCURSOR", line 338
      ORA-06512: at "UT3.UT_DATA_VALUE_REFCURSOR", line 333
      ORA-06512: at "UT3.UT_DATA_VALUE_REFCURSOR", line 386
      ORA-06512: at "UT3.UT_EQUAL", line 231
      ORA-06512: at "UT3.UT_EXPECTATION", line 26
      ORA-06512: at "UT3.UT_EXPECTATION", line 138
      ORA-06512: at "LOGICPRD.P_TEST_UT", line 41
      ORA-06512: at line 6
Finished in ,027149 seconds
1 tests, 0 failed, 1 errored, 0 disabled, 0 warning(s)
```

 I managed to reproduce this error with the minimal unit test given below. I also tried it with the newest version (v3.1.8.3190) and the same happens there.

# Version info
**Version**: 12.2.0.1.0
**Compatibility**: 12.2.0
**UT Version**: v3.1.7.3096
**v$version**: 
- Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
- PL/SQL Release 12.2.0.1.0 - Production
- "CORE	12.2.0.1.0	Production"
- TNS for Linux: Version 12.2.0.1.0 - Production
- NLSRTL Version 12.2.0.1.0 - Production

**nls_session_parameters**:
- NLS_LANGUAGE=ENGLISH
- NLS_TERRITORY=GERMANY
- NLS_CURRENCY=€
- NLS_ISO_CURRENCY=GERMANY
- NLS_NUMERIC_CHARACTERS=,.
- NLS_CALENDAR=GREGORIAN
- NLS_DATE_FORMAT=DD.MM.RR
- NLS_DATE_LANGUAGE=ENGLISH
- NLS_SORT=BINARY
- NLS_TIME_FORMAT=HH24:MI:SSXFF
- NLS_TIMESTAMP_FORMAT=DD.MM.RR HH24:MI:SSXFF
- NLS_TIME_TZ_FORMAT=HH24:MI:SSXFF TZR
- NLS_TIMESTAMP_TZ_FORMAT=DD.MM.RR HH24:MI:SSXFF TZR
- NLS_DUAL_CURRENCY=€
- NLS_COMP=BINARY
- NLS_LENGTH_SEMANTICS=BYTE
- NLS_NCHAR_CONV_EXCP=FALSE

**port_string**: x86_64/Linux 2.4.xx

# Client
Tried this using SQL Developer v18.2.0.183 and using the utplsl-cli 3.1.3.

# How to reproduce

Execute the following statements in the given order:

```sql
create table tmp_test ( id number, my_date date);

insert into tmp_test values (123, to_date('02-JAN-2019', 'DD-MON-YYYY'));

create or replace package p_test_ut as
    -- %suite(p_test)
    -- %suitepath(p_test)

    -- %test(test123)
    procedure test_proc;

end p_test_ut;
/
create or replace package body p_test_ut as
    procedure build_cursors (
        oc_expected out sys_refcursor,
        oc_actual out sys_refcursor,
        i_my_date in tmp_test.my_date%type
    )
    is
        lr_test tmp_test%rowtype;
    begin

        ut.set_nls();
        
        select * into lr_test from tmp_test where rownum = 1;
        
        open oc_expected for
            select  
                i_my_date as my_date
            from dual;

        -- fill cursor with actual table values.
        open oc_actual for
            select  
                my_date
            from tmp_test;
        
        ut.reset_nls();
    end build_cursors;
-- --------------------------------------------------------------------------
    procedure test_proc is
        lc_exp sys_refcursor;
        lc_act sys_refcursor;
    begin

        -- fill the two cursors with test a record each
        build_cursors (
            lc_exp, lc_act,
            to_date ('02-JAN-2019', 'DD-MON-YYYY')
        );

        -- compare variable with table values
        ut.expect (lc_act).to_equal (lc_exp);
    end test_proc;
end p_test_ut;
/

exec ut.run('p_test_ut');
```

It even happens by comparing the exact same date: 

```sql
open oc_expected for
    select  
        to_date ('02-JAN-2019', 'DD-MON-YYYY') as my_date
    from dual;

-- fill cursor with actual table values.
open oc_actual for
    select  
        to_date ('02-JAN-2019', 'DD-MON-YYYY') as my_date
    from dual;
```

I hope this descriptions helps tracking this bug down.
Thanks
